### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ezecopelandia** [colinhiggs/pyramid-jsonapi#153]
Hello, Im trying to use pyramid_jsonapi inside an application built with a pyramid framework called Websauna. I already have my API initialized, my endpoints and views are registered, and the database is being queried correctly when I do a GET request, I checked that on the sqlalchemy tab of the debug toolbar. 
The problem is that the response Im getting is always Internal Server Error. I attach the traceback that I get.
In the traceback says <Key error> related to a User class. Im not passing this class to pyramid_jsonapi on initalization because I dont want endpoints for that class, but that class is in a relationship with some classes that Im passing to pyramid_jsonapi. 

```Traceback (most recent call last):
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 101, in new_func
    result = func(self)  # pylint: disable=not-callable
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 236, in view_wrapper
    ret = func(self)  # pylint:disable=not-callable
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 608, in collection_get
    ret = self.collection_return(query, count=count)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 1373, in collection_return
    for dbitem in query.all()
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 1373, in <listcomp>
    for dbitem in query.all()
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 1722, in serialise_db_item
    rel_view = self.view_instance(rel.mapper.class_)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 2152, in view_instance
    return self.api.view_classes[model](self.request)
KeyError: <class 'websauna.system.user.models.User'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/src/websauna/websauna/system/auth/tweens.py", line 56, in __call__
    response = self.handler(request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 352, in authdebug_view
    return view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 513, in csrf_view
    return view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/eze-mac/Desktop/DESARROLLO/VOLALA/venv/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 123, in new_func
    raise HTTPInternalServerError("Unexpected server error.")
pyramid.httpexceptions.HTTPInternalServerError: Unexpected server error.```

**Comment by colinhiggs** [comment]
Firstly I'm sorry it has taken some time to get back to you.

The problem you are encountering seems to be a result of passing an inconsistent set of models to the api constructor - a situation I didn't anticipate. By inconsistent I mean that you have excluded a model which is referred to via relationships by other models.

It should be possible to detect when this occurs and remove any attempts to fetch or serialise related objects that would be outside the set of models provided. I'm thinking of this as a low priority piece of work, though, because the expected usage is to provide a consistent set of models.

Pull requests welcome if you have developed your own fix.
