### ISSUE TITLE
Sending HEAD requests to JSONAPI endpoints causes KeyError

### ISSUE THREAD

**Issue by kenneaal** [colinhiggs/pyramid-jsonapi#175]
Some libraries apparently like sending HEAD requests to endpoints. pyramid_jsonapi throws an exception on this because HEAD is not defined as a valid method.

Reproduction:
1) Set up a pyramid_jsonapi endpoint of any type
2) Send a HEAD request to the endpoint
3) PJ crashes with the following error:
`2020-03-31 15:14:10,994 ERROR [pyramid_debugtoolbar:280][waitress] Uncaught KeyError at http://sapi.fuelrats.dev/api/stats
traceback url: http://sapi.fuelrats.dev/_debug_toolbar/313430313739393635343837373630/exception
Traceback (most recent call last):
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 258, in toolbar_tween
    response = _handler(request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 178, in tm_tween
    reraise(*exc_info)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 143, in tm_tween
    response = handler(request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/fuelrats/SystemsAPI/systems_api/env/lib/python3.6/site-packages/pyramid_jsonapi/collection_view.py", line 99, in new_func
    ep_dict['endpoints'][endpoint]['http_methods'][method]['responses'].keys()
KeyError: 'HEAD'
`

**Comment by mrichar1** [comment]
There is scope in the library to add handling for new methods by modifying the `endpoints` object.

The documentation is here: https://colinhiggs.github.io/pyramid-jsonapi/customisation.html?highlight=cors#modifying-endpoints

For `HEAD` you probably want to do something like:

```
# Create a view class method.
def head_view(self):
    # Return an appropriate response to HEAD requests here
    return ''

pj = pyramid_jsonapi.PyramidJSONAPI(config, models, dbsession)

# Update all endpoints to handle HEAD http_method requests
for endpoint in pj.EndpointData.endpoints:
    # Update the renderer according to the type of data returned by head_view
    pj.EndpointData.endpoints[endpoint]['http_methods']['HEAD'] = {'function': 'head_view',
                                                                                                          'renderer': 'string'}

pj.create_jsonapi()

# Bind the head_view method to each view_class:
for vc in pj.view_classes.values():
        vc.options_view = head_view
```

Let us know if that does what you expect!

**Comment by kenneaal** [comment]
This is true, but PJ shouldn't cause an unhandled exception on being passed an otherwise entirely valid HTTP method, even if it is unsupported. IMO, it should be gracefully handled with a HTTPException returned by default, if the method should be considered invalid for the endpoint.

**Comment by mrichar1** [comment]
Yes - it shouldn't explode quite like that - it should probably return a better HTTP exception - I'll see if there are any hints in the jsonapi schema as to what the 'correct' status would be for that.

**Comment by colinhiggs** [comment]
> PJ shouldn't cause an unhandled exception on being passed an otherwise entirely valid HTTP method, even if it is unsupported

Yes, you're right there. I would consider that a bug.

**Comment by colinhiggs** [comment]
Meanwhile, there might be scope for adding some sort of default handling of HEAD requests even though they are not part of the JSONAPI spec. More thought required for that than just fixing the exception handling though.

**Comment by colinhiggs** [comment]
Just pushed a new branch `issue175` which adds a test and a fix for this. I realised just after pressing enter that I forgot to run the whole test suite before pushing (I just ran the new test) so I'll wait til the travis stuff is finished before creating a PR (assuming it comes back OK).

**Comment by colinhiggs** [comment]
Tests passed. @kenneaal do you want to test the new behaviour and potentially review the pull request? I'll wait a while for any potential answer before going ahead with a merge.

**Comment by kenneaal** [comment]
Looks good!
